cmake_minimum_required(VERSION 3.10)

set(TARGET_NAME BHive-Editor)

file(GLOB_RECURSE  SOURCE_FILES CMAKE_CONFIGURE_DEPENDS src/**.cpp)
file(GLOB_RECURSE  HEADER_FILES CMAKE_CONFIGURE_DEPENDS src/**.h)
source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${HEADER_FILES} ${SOURCE_FILES})

add_executable(${TARGET_NAME} ${HEADER_FILES} ${SOURCE_FILES})

set_target_properties(${TARGET_NAME} PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON FOLDER "BHive")
target_compile_definitions(${TARGET_NAME} PUBLIC EDITOR_RESOURCE_PATH="${CMAKE_CURRENT_SOURCE_DIR}/resources/")
target_link_libraries(${TARGET_NAME} PUBLIC BHive-Engine )
target_include_directories(${TARGET_NAME} PRIVATE src)

set(INSTALL_BIN "bin/${CMAKE_SYSTEM_NAME}/${CMAKE_BUILD_TYPE}")

install(TARGETS ${TARGET_NAME} DESTINATION ${INSTALL_BIN})