#include "TextureSpecification.h"

namespace BHive
{

	REFLECT(FTextureCreateInfo)
	{
		{
			BEGIN_REFLECT_ENUM(EMinFilter)(
				ENUM_VALUE(LINEAR), ENUM_VALUE(NEAREST), ENUM_VALUE(MIPMAP_LINEAR), ENUM_VALUE(MIPMAP_NEAREST), ENUM_VALUE(MIPMAP_LINEAR_NEAREST), ENUM_VALUE(MIPMAP_NEAREST_LINEAR)
			);
		}

		{
			BEGIN_REFLECT_ENUM(EMagFilter)
			(ENUM_VALUE(LINEAR), ENUM_VALUE(NEAREST));
		}

		{
			BEGIN_REFLECT_ENUM(EWrapMode)(ENUM_VALUE(REPEAT), ENUM_VALUE(CLAMP_TO_EDGE), ENUM_VALUE(MIRRORED_REPEAT), ENUM_VALUE(CLAMP_TO_BORDER));
		}

		{
			BEGIN_REFLECT_ENUM(EBorderColor)(
				ENUM_VALUE(FLOAT_TRANSPARENT_BLACK),
				ENUM_VALUE(FLOAT_OPAQUE_BLACK),
				ENUM_VALUE(FLOAT_OPAQUE_WHITE),
				ENUM_VALUE(INT_TRANSPARENT_BLACK),
				ENUM_VALUE(INT_OPAQUE_BLACK),
				ENUM_VALUE(INT_OPAQUE_WHITE)
			);
		}

		{
			BEGIN_REFLECT(FTextureCreateInfo)
			REFLECT_PROPERTY(MinFilter)
			REFLECT_PROPERTY(MagFilter)
			REFLECT_PROPERTY(WrapMode)
			REFLECT_PROPERTY(BorderColor);
		}
	}
} // namespace BHive
