#pragma once

#include "types/unordered_set.hpp"
#include "types/map.hpp"
#include "types/vector.hpp"
#include "types/filesystem.hpp"
#include "types/utility.hpp"
#include "types/string.hpp"
#include "types/optional.hpp"
#include "types/buffer.hpp"
#include "types/aabb.hpp"
#include "types/assethandle.hpp"
#include "types/assetmetadata.hpp"
#include "types/audio.hpp"
#include "types/bone.hpp"
#include "types/color.hpp"
#include "types/enumasbyte.hpp"
#include "types/glm.hpp"
#include "types/keyframe.hpp"
#include "types/lights.hpp"
#include "types/meshdata.hpp"
#include "types/scenecamera.hpp"
#include "types/skeletalnode.hpp"
#include "types/texture.hpp"


#include "Helpers.h"
#include "FileStream.h"
