#include "TextureSpecification.h"

namespace BHive
{

	REFLECT(FTextureSpecification)
	{
		{
			BEGIN_REFLECT_ENUM(EMinFilter)(
				ENUM_VALUE(LINEAR), ENUM_VALUE(NEAREST), ENUM_VALUE(MIPMAP_LINEAR), ENUM_VALUE(MIPMAP_NEAREST),
				ENUM_VALUE(MIPMAP_LINEAR_NEAREST), ENUM_VALUE(MIPMAP_NEAREST_LINEAR));
		}

		{
			BEGIN_REFLECT_ENUM(EMagFilter)
			(ENUM_VALUE(LINEAR), ENUM_VALUE(NEAREST));
		}

		{
			BEGIN_REFLECT_ENUM(EWrapMode)(
				ENUM_VALUE(REPEAT), ENUM_VALUE(CLAMP_TO_EDGE), ENUM_VALUE(MIRRORED_REPEAT), ENUM_VALUE(CLAMP_TO_BORDER));
		}

		{
			BEGIN_REFLECT(FTextureSpecification)
			REFLECT_PROPERTY(MinFilter)
			REFLECT_PROPERTY(MagFilter)
			REFLECT_PROPERTY(WrapMode);
		}
	}
} // namespace BHive
